-- @author smandrap
-- @description Go To Next-Previous track (context aware) pack
-- @version 1.0.0
-- @about
--   If Mixer has focus, go to next/previous track that is visible in the mixer (or add it to the selection).\n
--   Requires JS_Reascript API
-- @metapackage
-- @provides
--   [main] smandrap_Add next track in TCP or in Mixer to selection.lua
--   [main] smandrap_Add previous track in TCP or in Mixer to selection.lua
--   [main] smandrap_Select next track in TCP or in Mixer.lua
--   [main] smandrap_Select previous track in TCP or in Mixer.lua
