-- @author smandrap
-- @description Prompt name for subprojects (pack)
-- @version 1.4.1
-- @changelog
--   # You might notice i'm very dumb
--   + Add script to move each item to its own subproject.
--     Useful if doing sound design for a lot of separate clips and you want to leverage subprojects.
-- @about
--   EXPERIMENTAL!! No risks (uses native actions) but things may be quirky.
--   Please leave your feedback!
--
--   When creating a subproject, prompts for a name and optionally create it in a Subprojects folder.
--   Includes scripts to move items or tracks to subprojects, in dedicated folder and with your labeling.
-- @metapackage
-- @provides
--   [main] smandrap_Insert new subproject in Subproject folder (prompt for name).lua
--   [main] smandrap_Move items to subproject, prompt for name (non-destructive glue).lua
--   [main] smandrap_Move tracks to subprojects, prompt for name.lua
--   [main] smandrap_Move items to subproject individually (non-destructive glue).lua