-- @author smandrap
-- @description Prompt name for subprojects (pack)
-- @version 1.3
-- @changelog
--   + Refactor, more fixes
--   # Insert in subproject folder can't create a subdirectory atm. Will fix in the future. sorries
-- @about
--   When creating a subproject, prompts for a name and optionally create it in a Subprojects folder
-- @metapackage
-- @provides
--   [main] smandrap_Insert new subproject in Subproject folder (prompt for name).lua
--   [main] smandrap_Move items to subproject, prompt for name (non-destructive glue).lua
--   [main] smandrap_Move tracks to subprojects, prompt for name.lua
