-- @author smandrap
-- @description Prompt name for subprojects (pack)
-- @version 1.2
-- @changelog
--   - Fix a bunch of things, should be in working state (almost)
-- @about
--   When creating a subproject, prompts for a name and optionally create it in a Subprojects folder
-- @metapackage
-- @provides
--   [main] smandrap_Insert new subproject in Subproject folder (prompt for name).lua
--   [main] smandrap_Move items to subproject, prompt for name (non-destructive glue).lua
--   [main] smandrap_Move tracks to subprojects, prompt for name.lua
